# Form implementation generated from reading ui file 'settingsdialog.ui'
from PyQt5 import QtCore, QtWidgets


class UiSettingsDialog(object):
    def setup_ui(self, settings_dialog):
        settings_dialog.setObjectName("settings_dialog")
        settings_dialog.resize(330, 280)
        self.button_box = QtWidgets.QDialogButtonBox(settings_dialog)
        self.button_box.setGeometry(QtCore.QRect(10, 230, 311, 40))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel |
                                           QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.election_method_box = QtWidgets.QGroupBox(settings_dialog)
        self.election_method_box.setGeometry(QtCore.QRect(10, 10, 310, 180))
        self.election_method_box.setObjectName("election_method")
        self.highest_average_box = QtWidgets.QGroupBox(self.election_method_box)
        self.highest_average_box.setGeometry(QtCore.QRect(10, 20, 140, 150))
        self.highest_average_box.setCheckable(True)
        self.highest_average_box.setObjectName("highest_average")
        self.d_hondt_option = QtWidgets.QRadioButton(self.highest_average_box)
        self.d_hondt_option.setGeometry(QtCore.QRect(10, 30, 121, 20))
        self.d_hondt_option.setChecked(True)
        self.d_hondt_option.setObjectName("d_hondt")
        self.sainte_lague_option = QtWidgets.QRadioButton(self.highest_average_box)
        self.sainte_lague_option.setGeometry(QtCore.QRect(10, 60, 121, 20))
        self.sainte_lague_option.setObjectName("sainte_lague")
        self.huntington_hill_option = QtWidgets.QRadioButton(self.highest_average_box)
        self.huntington_hill_option.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.huntington_hill_option.setObjectName("huntington_hill")
        self.imperiali_ham_option = QtWidgets.QRadioButton(self.highest_average_box)
        self.imperiali_ham_option.setGeometry(QtCore.QRect(10, 120, 111, 20))
        self.imperiali_ham_option.setObjectName("imperiali_ham")
        self.largest_remainder_box = QtWidgets.QGroupBox(self.election_method_box)
        self.largest_remainder_box.setGeometry(QtCore.QRect(160, 20, 140, 150))
        self.largest_remainder_box.setCheckable(True)
        self.largest_remainder_box.setChecked(False)
        self.largest_remainder_box.setObjectName("largest_remainder")
        self.droop_option = QtWidgets.QRadioButton(self.largest_remainder_box)
        self.droop_option.setGeometry(QtCore.QRect(10, 60, 121, 20))
        self.droop_option.setObjectName("droop")
        self.hare_option = QtWidgets.QRadioButton(self.largest_remainder_box)
        self.hare_option.setGeometry(QtCore.QRect(10, 30, 121, 20))
        self.hare_option.setObjectName("hare")
        self.hare_option.setChecked(True)
        self.imperiali_option = QtWidgets.QRadioButton(self.largest_remainder_box)
        self.imperiali_option.setGeometry(QtCore.QRect(10, 120, 121, 20))
        self.imperiali_option.setObjectName("imperiali_lrm")
        self.hagenbasch_option = QtWidgets.QRadioButton(self.largest_remainder_box)
        self.hagenbasch_option.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.hagenbasch_option.setObjectName("hagenbasch")
        self.vote_label = QtWidgets.QLabel(settings_dialog)
        self.vote_label.setGeometry(QtCore.QRect(10, 200, 111, 20))
        self.vote_label.setObjectName("vote_label")
        self.vote_number = QtWidgets.QLineEdit(settings_dialog)
        self.vote_number.setGeometry(QtCore.QRect(130, 200, 191, 20))
        self.vote_number.setObjectName("vote_number")
        self.button_box.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setDisabled(True)

        self.retranslate_ui(settings_dialog)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslate_ui(self, settings_dialog):
        _translate = QtCore.QCoreApplication.translate
        settings_dialog.setWindowTitle(_translate("settings_dialog", "Settings"))
        self.election_method_box.setTitle(_translate("settings_dialog", "Election Methods"))
        self.highest_average_box.setTitle(_translate("settings_dialog", "Highest Average"))
        self.d_hondt_option.setText(_translate("settings_dialog", "D\'Hondt"))
        self.sainte_lague_option.setText(_translate("settings_dialog", "Sainte-Lague"))
        self.huntington_hill_option.setText(_translate("settings_dialog", "Huntington-Hill"))
        self.imperiali_ham_option.setText(_translate("settings_dialog", "Imperiali"))
        self.largest_remainder_box.setTitle(_translate("settings_dialog", "Largest Remainder"))
        self.droop_option.setText(_translate("settings_dialog", "Droop"))
        self.hare_option.setText(_translate("settings_dialog", "Hare"))
        self.imperiali_option.setText(_translate("settings_dialog", "Imperiali"))
        self.hagenbasch_option.setText(_translate("settings_dialog", "Hagenbasch"))
        self.vote_label.setText(_translate("settings_dialog", "Force # of votes:"))